"""empty message

Revision ID: 46f090b01d62
Revises: 4ae571f816cb
Create Date: 2023-05-17 17:45:30.743931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f090b01d62'
down_revision = '4ae571f816cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
        
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
        
    op.alter_column('todos', 'completed', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos','completed')

    # ### end Alembic commands ###
