"""empty message

Revision ID: 507dba4116f4
Revises: 81f2e1159d62
Create Date: 2023-05-25 17:44:04.024033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507dba4116f4'
down_revision = '81f2e1159d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
